apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transcept-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/transcept  # replace with your repo
    targetRevision: HEAD
    path: model_serving
  destination:
    server: https://kubernetes.default.svc
    namespace: transcept
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
